# Generated by Django 3.1.6 on 2021-11-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome do Agendamento:')),
                ('horario_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Horário Ínicio:')),
                ('horario_termino', models.DateTimeField(blank=True, null=True, verbose_name='Horário Término:')),
                ('concluido', models.BooleanField(max_length=194, null=True, verbose_name='Concluído:')),
                ('reajuste', models.BooleanField(max_length=194, null=True, verbose_name='Reajuste:')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita', verbose_name='Receita:')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'agendamento',
            },
        ),
        migrations.CreateModel(
            name='Horario_Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(blank=True, null=True, verbose_name='Horário:')),
                ('concluido', models.BooleanField(max_length=194, null=True, verbose_name='Concluído:')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.agendamento', verbose_name='Agendamento:')),
            ],
            options={
                'verbose_name': 'Horário do Agendamento',
                'verbose_name_plural': 'Horários dos Agendamentos',
                'db_table': 'horario_agendamento',
            },
        ),
    ]
