# Generated by Django 3.1.6 on 2021-04-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='concluido',
            field=models.BooleanField(max_length=194, null=True, verbose_name='Concluído:'),
        ),
    ]
