# Generated by Django 3.1.6 on 2021-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_auto_20210408_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='reajuste',
            field=models.BooleanField(max_length=194, null=True, verbose_name='Reajuste:'),
        ),
    ]
