# Generated by Django 3.1.6 on 2021-04-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_auto_20210408_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_agendamento',
            name='concluido',
            field=models.BooleanField(max_length=194, null=True, verbose_name='Concluído:'),
        ),
    ]
