# Generated by Django 3.1.6 on 2021-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome Completo:')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF:')),
                ('horario_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Horário do Cadastro no Sistema:')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome do Remédio:')),
                ('descricao', models.TextField(max_length=340, verbose_name='Descrição do Remédio:')),
            ],
            options={
                'verbose_name': 'Remédio',
                'verbose_name_plural': 'Remédios',
                'db_table': 'remedio',
            },
        ),
    ]
