# Generated by Django 3.1.6 on 2021-04-07 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome Completo:')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF:')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento:')),
                ('horario_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Horário do Cadastro no Sistema:')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário está ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário é da equipe de desenvolvimento')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Usuário é um superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome do Remédio:')),
                ('descricao', models.TextField(max_length=340, verbose_name='Descrição do Remédio:')),
            ],
            options={
                'verbose_name': 'Remédio',
                'verbose_name_plural': 'Remédios',
                'db_table': 'remedio',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.FloatField(verbose_name='Intervalo:')),
                ('quantidade_dias', models.IntegerField(default=0, help_text='total de dias que será consumido o remédio', verbose_name='Total de dias')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Ínicio:')),
                ('dosagem', models.IntegerField(verbose_name='Dosagem:')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pessoa:')),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.remedio', verbose_name='Remédio:')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'receita',
            },
        ),
    ]
