# Generated by Django 3.1.6 on 2021-04-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento:'),
        ),
    ]
