# Generated by Django 3.1.6 on 2021-04-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Usuário está ativo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Usuário é da equipe de desenvolvimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Usuário é um superusuario'),
        ),
    ]
