# Generated by Django 3.1.6 on 2021-12-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidade_UsuarioFK', to='usuarios.cidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(blank=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('P', 'Prefiro não dizer')], max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numeroResidencial',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número da residência'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
    ]
