# Generated by Django 3.1.6 on 2021-11-18 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=340, verbose_name='Descrição')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário registrado')),
            ],
            options={
                'verbose_name': 'Remédio',
                'verbose_name_plural': 'Remédios',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.FloatField(verbose_name='Intervalo')),
                ('quantidade_dias', models.PositiveIntegerField(default=0, verbose_name='Quantidade de dias')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Ínicio')),
                ('dosagem', models.PositiveIntegerField(verbose_name='Dosagem')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário registrado')),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedio_ReceitaFK', to='receitas.remedio', verbose_name='Remédio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_ReceitaFK', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
