# Generated by Django 3.2 on 2021-12-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_agendamento',
            name='concluido',
            field=models.BooleanField(default=False, max_length=194, null=True, verbose_name='Concluído:'),
        ),
    ]
